public = "public"
cleanUrls = true
trailingSlash = false
etag = true
directoryListing = true

[[rewrites]]
source = "/app/**"
destination = "/index.html"

[[redirects]]
source = "/old-page"
destination = "/new-page"
type = 301

[[headers]]
source = "/**"
[[headers.headers]]
key = "Cache-Control"
value = "max-age=7200"

ignore = [".env", "node_modules/**"]
